### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ezoheux** [limeberry/framework#19]
Consider splitting your framework into components. For example, dataman would have its own repository and io would have its own repository. Then make them composer packages and have them installed via composer once the create project composer command is used. This makes it easy to update and test components individually. So if one repository is failing you can narrow down the error. Also we need to start writing tests to ensure your code works.

**Comment by sinansalih** [comment]
hello @ezoheux thanks for your suggestions. As you mentioned İ tried splitting packages of framework but because autoloading done in autoloader.php file (and not by composer) in limeberry İ did not managed to get the required packages (aka: io, forms, dataman etc) in the specific directory İ want ( in ./limeberry/) . İ do not have the enough knowledge on composer to make it possible to load required packages (splitted packages) to directory where limeberry looks for classes(./limeberry/).

If there is a way to get required packages downloaded not to "project_root/vendor" but to "project_root/limeberry" path could you please modify the limeberry/framework/composer.json and limeberry/autopulse/composer.json files.


the src/ path in autopulse needs to be downloaded in limeberry folder where other core classes are when creating.

**Comment by ezoheux** [comment]
I have enough knowledge i can make a pull request fixing composer autoloading. Also if you want i can split them into different repositories and link them together through composer.

**Comment by sinansalih** [comment]
thank you very much @ezoheux I would be pleased. I have created a repository called autopulse make a pull request with correct json configuration to install that package to limeberry folder on create project. this is an empty depository just a text file inside. I will slipt database classes and migration classes there later.

**Comment by sinansalih** [comment]
All packages (except required for core code) splitted to repositories and get as a composer package when creating project.
